# makefile : makes the ABC program
runbaby : learn_cpp.o ### by typing „make“, the makefile generates an executable denotes as „abc“ g++ ­o abc a.o b.o c.o

learn_cpp.o : learn_cpp.cpp
	g++ ­learn_cpp.cpp

clean : ### by typing „make clean“, the executable, the *.mod as well as the *.o files are deleted
	rm *.mod *.o abc
